### ISSUE TITLE
CI changes needed

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1336]
## P1 (ASAP)
In order to be able to release as open source we require the following

- [x] Hub credentials for pushing on branch and tag builds only @talex5 
- [x] No credentials on PR builds @talex5 
- [ ] Be happy about the security story for running on public PRs - @riyazdf to sign off

We would like to have

- [x] QEMU tests as we have now, absolute minimum
- [x] GCP test runs on disposable VMs
  - [x] GCP support in `moby run` #1423
  - [x] Changes to MobyCI @talex5 

## P2 (For Dockercon)

- [x] LTP tests (frequency TBD)
  - [x] LTP Test runner #1230 
  - [x] Decide on when tests should be run @dave-tucker
  - [x] Changes to MobyCI @talex5 

## P3 (Afer Dockercon)

- [x] QEMU EUFI tests on every PR
  - [x] QEMU UEFI support in `moby run` #480 
  - [x] Changes to MobyCI @talex5 
- [ ] Tests on OSX/hyperkit #954 
  - [x] Set up a machine on macstadium.com for tests @dave-tucker
  - [ ] Changes to MobyCI @talex5
- [ ] Tests on AWS
  - [x] AWS support in `moby run` #714
  - [ ] Changes to MobyCI @talex5 
- [ ] Hyper-V LIS tests 
  - [ ] Hyper-V build and LIS test targets in Makefile #1229
  - [ ] Provision a Windows Server 2012 VM on packet.net for LIS @dave-tucker
  - [ ] Changes to MobyCI @talex5
- [ ] Tests on Azure (requires porting Azure support from editions first)
- [ ] Tests on VMWare (after VMWware support merged)
- [ ] Tests on BlueMix (after support merged)
