### ISSUE TITLE
[tracking] ARM boot status

### ISSUE THREAD

**Issue by avsm** [linuxkit/linuxkit#1377]
Tracking issue for booting Moby on ARM 32/64.

Design notes:
- We would like to build Moby natively instead of cross-compile, so we need server-grade hosting of both ARM32 and ARM64 in order to automate.
- Desktop builds could happen slowly using binfmt/qemu (enabled by default in Docker for Mac/Win) but we primarily want to support bare hardware.
- Ideally our kernel would diverge as little as possible from upstream Moby (which in turn aims to track upstream Linux).  This may mean only supporting a modern subset of hardware which are upstream friendly.
- Do we want to support ARM32 at all? Rpi3 (the most popular embedded ARM) supported [64bit just fine](https://en.opensuse.org/HCL:Raspberry_Pi3).

Ongoing tasks:
- [x] Port kernel/ to also build ARM64 options. @mor1 
- [x] Base Alpine aarch64 images for the build images. Probably not using multiarch and instead selecting the "arm64" hash in the Makefile instead. There has been some discussion in Docker community slack with @DieterReuter about using [multiarch manifests](https://github.com/portainer/docker-manifest/blob/master/portainer.yml) via @estesp's manifest tool.
- [ ] No autobuilds for ARM, so need to build all the relevant Hub images from scratch, probably via a [DataKitCI](https://github.com/docker/datakit) instance running on a fast hosted ARM64. @avsm or @talex5
- [x] Try the [1.12.1 aarch64 build](https://github.com/sealsystems/arm-docker-engine-deb) to bootstrap latest docker/docker and find out the state of ARM64. @RobbKistler 
- [ ] For MirageSDK applications, port of [solo5 to support multiarch](https://github.com/Solo5/solo5/pull/171) is ongoing, which will give [arm64 support](https://github.com/Solo5/solo5/issues/151) - @mato and @djwillia

Hardware notes:
- [packet.net](http://packet.net) has provided excellent hosted ARM64 machines.  They have a 64-bit only 96-core Cavium ([specs](https://www.packet.net/bare-metal/servers/type-2a/)) and also a 32-core machine which is in closed preview, but crucially supports both 32- and 64-bit mode in the processor.  Contact @avsm to get access to the preview machine.  Also these boxes support [ipxe](http://ipxe.org) so we can get custom kernels running on them (#1245).
- [Scaleway](http://scaleway.com) has low end ARM32 boxes, but these are 4 core only so not ideal for builds (but possibly good for bare metal CI).
- RPi3 would be awesome -- @DieterReuter has expressed interest.  [Mythic beasts](https://www.mythic-beasts.com/order/rpi) may be an option for hosted builds in Cambridge -- need to contact them to find out if this is possible.

Will continue to edit this issue as it develops!

**Comment by rneugeba** [comment]
removed milestone

**Comment by vielmetti** [comment]
@mor1 - I am now tracking this issue - let me know if anything comes up that I can help with.

**Comment by techninja1008** [comment]
Any progress? Would really like to use this on a raspberry pi as an IoT device.

**Comment by mor1** [comment]
Sorry, forgot to update. I have now built and booted a kernel with an initrd based off the `minimal.yml` example on a packet.net type 2A host :)

@techninja1008 You're welcome to try and use the content of `projects/arm64/` in my `project-arm64` branch if you wish, though it lags `master` currently (RFC PR that is rather messy at #1654).

That completes, to my mind, the PoC. Following a chat with @rneugeba last week, here are the things that we think need addressing to integrate this, with reference to outstanding issues:
* expose container registry (org) #1824
* multiarch support
  * builds #1242 #1377
  * will we need multiarch `Dockerfile`s too? (possibly not given a multiarch alpine base?)
  * allow selection of arch in `.yml` config #1847
  * `DOCKER_CONTENT_TRUST=1` fails for `aarch64/alpine` and derived images #1195
* kernel config management (arch/version/custom patches) #1151 #635 #1787
* `packet.net` network device drivers #1245

**Comment by techninja1008** [comment]
Great to hear. Could I possibly give my two cents to the problem based on a
shower thought?
If you have a second mini filesystem root with its own section similar to
`init` for holding architecture specific data (thinking dtbs, bootloader
etc.) And then make this available in a tar as well as everything else
(root filesystem, kernel, etc. In their own tars) to a docker container run
at build by piping them through stdin running a user specified image, and
then expecting a tar of the output image file(s) through stdout, it allows
the Moby tool to support pretty much an arch as long as images are made for
it.

Just a shower thought.

On 17 May 2017 7:43 a.m., "Richard Mortier" <notifications@github.com>
wrote:

Sorry, forgot to update. I have now built and booted a kernel with an
initrd based off the minimal.yml example on a packet.net type 2A host :)

@techninja1008 <https://github.com/techninja1008> You're welcome to try and
use the content of projects/arm64/ in my project-arm64 branch if you wish,
though it lags master currently (RFC PR that is rather messy at #1654
<https://github.com/linuxkit/linuxkit/pull/1654>).

That completes, to my mind, the PoC. Following a chat with @rneugeba
<https://github.com/rneugeba> last week, here are the things that we think
need addressing to integrate this, with reference to outstanding issues:

   - expose container registry (org) #1824
   <https://github.com/linuxkit/linuxkit/issues/1824>
   - multiarch support
      - builds #1242 <https://github.com/linuxkit/linuxkit/issues/1242>
      #1377 <https://github.com/linuxkit/linuxkit/issues/1377>
      - will we need multiarch Dockerfiles too? (possibly not given a
      multiarch alpine base?)
      - allow selection of arch in .yml config #1847
      <https://github.com/linuxkit/linuxkit/issues/1847>
      - DOCKER_CONTENT_TRUST=1 fails for aarch64/alpine and derived images
      #1195 <https://github.com/linuxkit/linuxkit/issues/1195>
   - kernel config management (arch/version/custom patches) #1151
   <https://github.com/linuxkit/linuxkit/issues/1151> #635
   <https://github.com/linuxkit/linuxkit/issues/635> #1787
   <https://github.com/linuxkit/linuxkit/pull/1787>
   - packet.net network device drivers #1245
   <https://github.com/linuxkit/linuxkit/issues/1245>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/1377#issuecomment-302000437>,
or mute the thread

**Comment by zlim** [comment]
cc @arm64b

**Comment by arm64b** [comment]
Hi All,
I'd like to share our latest ARM64 support on LinuxKit project, please see: [https://github.com/arm64b/linuxkit-arm64/tree/aarch64](url)
As followed, I will create some PRs to reach to the goal of multi-arch support with one code base gradually,
any suggestions are appreciated :-)

@justincormack @rn @avsm @mor1 @ijc @dave-tucker @RobbKistler

**Comment by justincormack** [comment]
@arm64b cool. We really need a multi arch base alpine image as a starting point. I known @tianonis working on these for the official images, which is a good start.

**Comment by arm64b** [comment]
@justincormack  Now alpine 3.6 for ARM64 is under arm64v8/alpine:3.6, we need to unify the base alpine image first. My proposal is, we use linuxkit as the ORG for both amd64 and arm64, the tag can be used to identify the image for different ARCH, that means we need to add the ARCH into the hash calculation. looks like:
linuxkit/alpine: a9b43ebb524e43a71001006c70921352adcbf6c5  (for amd64)
linuxkit/alpine: eec43bb8db512e3673747db4940321517c1b8519 (for arm64)
Does that make sense?  Justin, would you please point me to the work of @tianonis ? I can't find that.

**Comment by justincormack** [comment]
Sorry that was a typo for @tianon who works on the official images. The experimental multi arch support is at https://hub.docker.com/u/trollin/ but many of the images actually only included a single arch (but with the manifest) last time I looked.

**Comment by mor1** [comment]
`aarch64/alpine` is an AARCH64 Alpine image.

The relevant PR for the CLI builds just fine on ARM64, and I've managed to run it to try to start creating things but haven't actually successfully made a multiarch image yet. (Mobile coverage on the train was too spotty.)

**Comment by vielmetti** [comment]
https://hub.docker.com/r/arm64v8/alpine/ is also an AARCH64 Alpine image (there was a Great Renaming of ARM images).

**Comment by tianon** [comment]
Indeed, the Alpine image isn't officially multiarch yet (the images that are up now are something I built by consuming the official Alpine release tarballs directly).

**Comment by arm64b** [comment]
http://container-solutions.com/multi-arch-docker-images/ is a good solution for multiarch docker image,
seems there's no technical obstacle to do that. If we have a multi-arch alpine:3.6 as the base image, then we don't need to change the tools/alpine/Dockerfile at all

**Comment by arm64b** [comment]
@justincormack @tianon @vielmetti @mor1 @ijc @avsm @zlim @rn @RobbKistler ...
Now the ARM64 support for LinuxKit need to address below issues:
1. multiarch of the alpine base image.  Not ready now, if someone want to play with LinuxKit on ARM64, they need to have a workaround to replace the 'FROM alpine:3.6' in the Dockerfile to 'FROM arm64v8/alpine:3.6', then he need to resolve another issue as below -
2. ovmf pkg is missed in the arm64v8/alpine:3.6, but this pkg can be simply ignored on ARM64, this will not affect the boot progress of the kernel. So this is not a big issue to run the LinuxKit image. But we will have another feature as below -
3. ARM64 UEFI support. With that we can generate ACPI table in this FW.  This will include both local qemu and qemu container.

**Comment by arm64b** [comment]
ARM64 UEFI can be found at https://github.com/tianocore/edk2.git

**Comment by liqdfire** [comment]
I am trying to build the branch from @arm64b [https://github.com/arm64b/linuxkit-arm64/tree/aarch64](url) on my Jetson TX2 and am stuck on building the tools. 

Trying to build the alpine tool, the image arm64b/shellcheck:v0.4.6 is missing from docker hub.
I pulled the source shellcheck, and started building the base images up the stack; however, the arm64v8/alpine:3.6 is missing the GHC / Cabal which looks to have been included in base alpine according to [https://github.com/mitchty/alpine-linux-ghc-bootstrap](url)

My next step is to build an arm64v8 alpine and add cabal. I guess I am mostly looking for confirmation that I am not missing something obvious from those that have pulled that branch and successfully built. Mind you I am doing this on a fresh system, running Ubuntu 16.04. So I had to pull Go 1.8.3, Docker-CE 17.06, containerd, runc, and all build from source, as the only thing available in the ubuntu repos for 16.04 is Docker 1.12.

**Comment by justincormack** [comment]
@liqdfire we have removed shellcheck from the alpine package upstream, as it is annoying to build and not being used at present (it is only to check the source, so we can do that by other means)

**Comment by justincormack** [comment]
(I think @arm64b did have a working package somewhere, but I would not bother)

**Comment by liqdfire** [comment]
@justincormack to make sure i understand, I should be able to remove these 3 lines from the alpine tool dockerfile and the rest of the build will will work just fine?

https://github.com/arm64b/linuxkit-arm64/blob/aarch64/tools/alpine/Dockerfile#L41
https://github.com/arm64b/linuxkit-arm64/blob/aarch64/tools/alpine/Dockerfile#L52
https://github.com/arm64b/linuxkit-arm64/blob/aarch64/tools/alpine/Dockerfile#L53

**Comment by justincormack** [comment]
Yes, see https://github.com/linuxkit/linuxkit/pull/2189

**Comment by liqdfire** [comment]
@justincormack  got it, thanks!

**Comment by arm64b** [comment]
@liqdfire @justincormack  About the shellchecke, yes, I build that in my local machine, but for internal legal reason, I can't release some kinds of binaries in the hub. Fortunately, just as Justin mentioned, the shellcheck has been removed from the latest code base. We'll be very close to use the LinuxKit mainline to support ARM64...

**Comment by rn** [comment]
proposal for `x86_64`/`arm64` multiarch manifest is here: https://github.com/linuxkit/linuxkit/issues/2292

**Comment by arm64b** [comment]
@rn  will be a significant milestone for support ARM64 👍

**Comment by loxeye** [comment]
@arm64b The makefile in aarch64 branch of https://github.com/arm64b/linuxkit-arm64 is pointing to arm64b docker hub image which don't seem to exist anymore. Am I using the wrong repository to build an arm64 linuxkit?

**Comment by arm64b** [comment]
> @arm64b The makefile in aarch64 branch of https://github.com/arm64b/linuxkit-arm64 is pointing to arm64b docker hub image which don't seem to exist anymore. Am I using the wrong repository to build an arm64 linuxkit?

arm64b is my personal account in the hub, but for some internal legal reason, binary release is forbidden from us. So my suggestion is, build your own arm64 docker image locally (if you already have a account in the hub and the legal is not the problem from your organization, you can push to the hub absolutely):
`/tools/alpine$make ORG=loxeye NOTRUST=1`
then you will get a alpine docker image like this:
 `loxeye /alpine:hash_value`
For the kernel, you can also build the image like:
`kernel$make ORG=loxeye build_4.11.x NOTRUST=1`
then you will get the kernel docker image: loxeye/kernel:xxxx

After you finished all the docker image in the linuxkit.yml from my branch, then you need to replace all the images in the YAML file with the images you just built.
Before you build the bin/moby and bin/linuxkit, change the top level Makefile and change the go-compile image with the one you just built. Another image need to replace is in the src/cmd/linuxkit/run_qemu.go, where you need to change the qemu image with the one of your own if you don't have a local qemu-system-aarch64 binary installed.
Now you can build the 2 tools:
`$make bin/moby
$make bin/linuxkit'
After that you will have the 2 tools, then
`$bin/moby build linuxkit.yml`
You will get two files: `linuxkit-kernel` and `linuxkit-initrd.img`, now you can run it with:
`$bin/linuxkit run qemu -arch "aarch64" linuxkit`
You will enter into a name-spaced system if everything is OK. enjoy the trip!

**Comment by rn** [comment]
Master now has full arm64 support and you can build arm64 images from the same YAML you build x86 linuxkit images from. There are a few minor niggles for which I'll file separate issues. I'm inclined to close this issue...objections?
