### ISSUE TITLE
DockerCon and open source planning

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1429]
This issue tracks *some* high level items for DockerCon and open source releasing. There are four milestones associated with this:
- [DockerCon-2](https://github.com/docker/moby/milestone/7): Items which should be addressed roughly two weeks before DockerCon
- [DockerCon-1](https://github.com/docker/moby/milestone/6): Items which should be addressed roughly one week before DockerCon. These are mostly demo related items
- [DockerCon](https://github.com/docker/moby/milestone/4): Items which should be addressed by DockerCon. These are mostly related to open source preparation
- [Post DockerCon](https://github.com/docker/moby/milestone/8): Items which could happen after DockerCon.

Items also have priority labels.

- Naming
  - [x] *Decide on a Name* (#1416)
  - [ ] Update repository, tools, documentation, docker hub org etc with new name (#1417)
- Repository
  - [ ] License/Contributing/Maintainer texts (#1418)
  - [ ] Review for open-source readiness (#1419)
  - [ ] Cleanup build/layout (#1266)
- `moby` CLI
  - [x] Verbose output on build (#1233)
  - Additional `moby build` issues
    - [ ] Add `moby.yml` to initrd (with sha256 tag) (#1231)
    - [ ] AMI output (#1420)
    - [ ] Azure output (#1421)
  - Additional `linuxkit run` targets
    - [x] Most of the below require (#1433)
    - [x] `qemu/kvm` (#1383)
    - [x] GCP (#1423)
    - [ ] packet.net x86 (#1424)
    - [x] VMware fusion/player (#1422)
- Security
  - [x] Document security architecture (#1437)
  - [x] Decide what to demo security related (#1425)
  - [x] ~~Implement demo (one week more or less, stacked on #583 )~~ Not needed. It will be in the script
  - [x] Readonly root filesystem (#583) 
- Distribution/infrakit
  We'd really like to have a cluster based demo
  - simple `etcd` cluster setup on HyperKit
    - ~~`etcd` infrakit flavour [M-1/P0]~~ Will use the vanilla flavour with hardcoded IPs
    - ~~Userdata data handling in Moby [M-1/P0]~~ Not needed with hard coded IPs
    -[x] `etcd` infrakit cluster setup on GCP/AWS
- ARM (packet.net, Odroid C2?)
  - [ ] Initial ARM support (#1377)
  - [ ] Easy to use/demo ARM support (this is a stretch, i think)
- Packages
  - [ ] Init (#1426)
  - [ ] Logging (#904)
  - [ ] Diagnostics (#1427)
- Documentation
  - [ ] Get started guide/workflow document (#1026)
- Unikernel/SDK (post dockercon, needs tracking issue)
- CI
  - Build packages, notary sign, and push to hub in CI (#1074)
  - Run tests in CI (see #1336, should be split into appropriate sub issues):
    - [ ] Test all output types with qemu (DockerCon/P0)
    - [ ] Unit tests for `moby` outputs (#1428)
    - [ ] Test bare metal x86 (DockerCon/P1)
    - [ ] Test on GCP x86 (post DockerCon/P1)
    - [ ] Test on GCP x86  (post DockerCon/P1)
    - [ ] Run LTP on bare metal (#1230)
    - [ ] Run virtsock stress tests on macOS/Windows (post DockerCon/P1)

**Comment by AkihiroSuda** [comment]
Why this repo is not under `github.com/moby`?

**Comment by fntlnz** [comment]
"Additional `moby run` targets"
now is:
"Additional `linxukit run` targets"

**Comment by riyazdf** [comment]
@fntlnz fixed

**Comment by rneugeba** [comment]
closing this as outdated and not in use anymore
