### ISSUE TITLE
[tracking] Packet provider support open issues and missing features

### ISSUE THREAD

**Issue by vielmetti** [linuxkit/linuxkit#2064]
**Description**

"it would be good to open an issue that lists all the missing features as a checklist."

Reference 

**Steps to reproduce the issue:**

Boot Linuxkit on Packet, notice that it's not feature complete. Examine [run_packet.go](https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/run_packet.go) and notice some TODOs.

**Feature checklist**

Somewhat ordered by ease of implementation, work in progress, or need

- [ ] Improved documentation
- [ ] Persistent PXE boot support
- [ ] "User data" to support boot status reporting
- [ ] TODO: poll events api for bringup (requires extpacknogo)
- [ ] TODO: connect to serial console (requires API extension to get SSH URI)
- [ ] TODO: add ssh keys via API registered keys
- [ ]  Storage support via on-board SSD and/or HDD
- [ ] Boot on Type 2A (ARMv8)
- [ ] Boot on Type 2 (Intel, bonded Mellanox NICs)
- [ ] Bonding of network cards on devices that support that
- [ ] Boot on Type S (multiple HDD)

**Comment by rn** [comment]
thank you for putting this together

**Comment by vielmetti** [comment]
#1245 has some of this discussion and some additional detail

**Comment by vielmetti** [comment]
#1377 has some specifics and tracks the "type 2a" ARM issue

**Comment by vielmetti** [comment]
Updated to reflect #2376 changes for always-on PXE, serial console.

**Comment by vielmetti** [comment]
Add #2378 for RAID support on Type 2's.

**Comment by vielmetti** [comment]
Updated to reflect that #2376 has been merged.

**Comment by justincormack** [comment]
#2438 fixes metadata, userdata, ssh keys, bonding.

**Comment by vielmetti** [comment]
Added #2434 as an open issue, Networking on Cavium Thunder is not quite working (4.9.x kernel).

**Comment by rn** [comment]
@vielmetti with https://github.com/linuxkit/linuxkit/pull/2852 we changed iPXE support and now load the iPXE script via an URL instead of user-data. This frees up the userdata for metadata and other stuff.
