### ISSUE TITLE
`projects/kubernetes` improvements/updates

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2236]
Transcribed from https://github.com/linuxkit/linuxkit/pull/2228#issuecomment-315732254, will edit and add as other things occur to me etc:
* [x] Sort out build of image-cache images (see #2239)
* [x] Update to newer kube and weave (see #2291).
* [x] Use `pkg/metadata` (was in #2228 already)
* [x] Replace use of alpine onboot service for a simple `mkdir` (on the persistent disk after `pkg/mount` or `pkg/format`) somehow. (see #2307)
* [x] Make `ssh_into_kubelet.sh` work with `boot.sh` on Linux (without breaking MacOS!). Script may already be broken due to switch to `ctr` etc anyway (see #2291)
* [x] Network connectivity between nodes when running with QEMU on Linux (perhaps `listen=` on master and `connect=` on nodes?) (see #2291)
* [x] Try to reduce sizes of everything (see #2239, #2291, #2393)

**Comment by zacheryph** [comment]
For what its worth this appears to not work on MacOS anymore either.  I'm new to all of this but it appears `-publish` is no longer (never was?) an option for the hyperkit "provider".

```console
# Sierra 10.12.5
$ ./boot.sh
+ rm -rf kube-master-state
+ ../../bin/linuxkit run -publish 2222:22 -cpus 2 -mem 4096 -state kube-master-state -disk size=4G -data '' kube-master
flag provided but not defined: -publish
```

**Comment by justincormack** [comment]
Would be nice to update to 1.7 as well.

**Comment by ijc** [comment]
All done, I think.
