### ISSUE TITLE
Improve / finish conversion to `linuxkit pkg`

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2587]
Tracking things which aren't yet done:
- [ ] #2583  switch kernel build to `linuxkit pkg`.
- [ ] #2584  embed `push-manifest.sh` into `linuxkit pkg`.
- [ ] #2584  convert `tools/guestfs`.
- [ ] #2586  convert `tools/alpine`.
