### ISSUE TITLE
open source moby

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#65]
Checklist of what needs to be done before open sourcing (incomplete)
- [ ] remove old binary builds #6 
- [ ] merge Windows build
- [ ] clean up arm build #33 #34 
- [ ] testing, CI linked to github
- [ ] review included pinata code
- [ ] release schedule
- [ ] remove daemons used by pinata and move to pinata repo
- [ ] clean up config so there is a single config API #71
