### ISSUE TITLE
improve build/CI speed

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#958]
Build is a bit slow, especially from cold cache. We use Docker cache well, but the build process is not ideal.

Things we could do
- [ ] make the kernel builds into base images, so they are not rebuilt except when they change - maybe after #957 
- [ ] fix #450 so there is less repetition might help.
- [ ] build less, by pulling from external repos, eg `docker/diagkit` for diagnostics.
- [x] change the CI to do the different flavour builds (currently standard and aufs, but later LTS kernel and latest) in parallel. #959

**Comment by justincormack** [comment]
obsolete
